# Generated by Django 3.2.8 on 2022-10-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_bitcoin_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='coin',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
