# Generated by Django 3.2.8 on 2022-10-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_bitcoin_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='minmax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
    ]
