# Generated by Django 3.2.8 on 2022-10-20 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_minmax'),
    ]

    operations = [
        migrations.AddField(
            model_name='minmax',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
